name : Reusable   Workflow 
on:
  workflow_call:
    inputs:
      name:
        description: 'Input description:'
        type: string
        default: 'Ali'
        required: false
    secrets:
      access-token:
        description: 'Secret description:'
        required: true
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    uses: action/checkout@v3
    run: ls -a   
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name : Display Github Context 
        run: echo '${{ toJson(github)}}'
      - name: Display name inputs
        run: echo '${{ inputs.name}}'
      - name: Display access-token secret
        run: echo '${{ secret.access-token}}'


      

